version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - hive-buffet-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s     
      retries: 15       

  hive-buffet:
    build:
      context: .
      dockerfile: Dockerfile
    image: hive-buffet:test
    container_name: hive-buffet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HiveBuffetDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__IdentityConnection=Server=sqlserver;Database=HiveBuffetUserDb;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - hive-buffet-network

networks:
  hive-buffet-network:
    driver: bridge
